name: ipin
description: Ipin encryption for EBS / noebs. ipin uses a very simple interface to calculate encrypted ipin for both EBS / noebs use cases. ipin is battle tested and used in production by different companies.
repository: "https://github.com/noebs/ipin.dart"
version: 0.0.5
homepage: "https://docs.noebs.dev"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypton: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
